characters = [
    {   id: 1,
        name:'Luke Skywalker',
        birth_year: '19BBY',
        birth_planet: 'Tatooine',
        gender: 'Male',
        image: './images/luke.jpg'
    },
    {   id: 2,
        name:'Leai Skywalker',
        birth_year: '19BBY',
        birth_planet: 'Polis Massa',
        gender: 'Female',
        image: './images/leai.jpg'
    },
    {   id: 3,
        name:'Darth Vader',
        birth_year: '41BBY',
        birth_planet: 'Tatooine',
        gender: 'Male',
        image: './images/darthvader.jpg'
    },
    {   id: 4,
        name:'Palpatine',
        birth_year: '82BBY',
        birth_planet: 'Naboo',
        gender: 'Male',
        image: './images/palpatine.jpg'
    },
    {   id: 5,
        name:'Bobba Fett',
        birth_year: '32BBY',
        birth_planet: 'kamino',
        gender: 'Male',
        image: './images/boba.jpg'
    },
    {   id: 6,
        name:'Han Solo',
        birth_year: '32BBY',
        birth_planet: 'Corellia',
        gender: 'Male',
        image: './images/hansolo.jpg'
    },
    {   id: 7,
        name:'Yoda',
        birth_year: '8962BBY',
        birth_planet: 'Grentarik',
        gender: 'Male',
        image: './images/yoda.jpg'
    },
    {   id: 8,
        name:'Darth Maul',
        birth_year: '54BBY',
        birth_planet: 'Dathomir',
        gender: 'Male',
        image: './images/darth-maul.jpg'
    },
    {   id: 9,
        name:'Grand Moff Tarkin',
        birth_year: '64BBY',
        birth_planet: 'Eriadu',
        gender: 'Male',
        image: './images/tarken.jpg'
    },
    {   id: 10,
        name:'Jabba the hutt',
        birth_year: '600BBY',
        birth_planet: 'Nul Hutta',
        gender: 'Male',
        image: './images/jabba.jpg'
    },
    {   id: 11,
        name:'Chewbacca',
        birth_year: '200BBY',
        birth_planet: ' Kashyyyk',
        gender: 'Male',
        image: './images/chewy.jpg'
    },
    {   id: 12,
        name:'Lando Calrissian',
        birth_year: '43BBY',
        birth_planet: 'Socorro',
        gender: 'Male',
        image: './images/lando.jpg'
    },
    {   id: 13,
        name:'C-3PO',
        birth_year: '12BBY',
        birth_planet: 'Tatooine',
        gender: 'other',
        image: './images/c3pio.jpg'
    },
    {   id: 14,
        name:'Obi-Wan Kenobi',
        birth_year: '57BBY',
        birth_planet: 'Stewjon',
        gender: 'Male',
        image: './images/obi-wan.jpg'
    },
]